CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true

DISTORT_IMAGE: true
BACKBONE: 'resnet'
MODEL: 'voxelpose'
DATA_DIR: ''
GPUS: '1'
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 4
PRINT_FREQ: 100

DATASET:
  COLOR_RGB: True
  ROOT: "data/Panoptic"
  TRAIN_DATASET: 'panoptic'
  TRAIN_HEATMAP_SRC: 'image'
  TEST_DATASET: 'panoptic'
  TEST_HEATMAP_SRC: 'image'
  ROOTIDX: 2
  CAMERA_NUM: 5
  NUM_JOINTS: 15
  ORI_IMAGE_WIDTH: 1920
  ORI_IMAGE_HEIGHT: 1080

NETWORK:
  PRETRAINED_BACKBONE: "models/pose_resnet50_panoptic.pth.tar"
  TARGET_TYPE: gaussian
  IMAGE_SIZE:
  - 960
  - 512
  HEATMAP_SIZE:
  - 240
  - 128
  SIGMA: 3

LOSS:
  USE_TARGET_WEIGHT: true
TRAIN:
  BATCH_SIZE: 8
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 10
  RESUME: false
  OPTIMIZER: adam
  LR: 0.0001
TEST:
  MODEL_FILE: 'model_best.pth.tar'
  BATCH_SIZE: 1
DEBUG:
  DEBUG: true
  SAVE_HEATMAPS_GT: true
  SAVE_HEATMAPS_PRED: true
CAPTURE_SPEC:
  SPACE_SIZE:
    - 8000.0
    - 8000.0
    - 2000.0
  SPACE_CENTER:
    - 0.0
    - -500.0
    - 800.0
  VOXELS_PER_AXIS:
    - 80
    - 80
    - 20
  MAX_PEOPLE: 10
  MIN_SCORE: 0.3
INDIVIDUAL_SPEC:
  SPACE_SIZE:
    - 2000.0
    - 2000.0
    - 2000.0
  VOXELS_PER_AXIS:
    - 64
    - 64
    - 64
